### ISSUE TITLE
Unable to use mod with Aternos servers

### ISSUE THREAD

**Issue by NothingWorks123** [ShaneBeee/EnchBook#12]
The mod is currently not able to be used with Aternos servers due to the fact that Aternos servers only allow approved plugins. Sadly, it can only approve plugins that have no external downloads (such as GitHub), and also is downloaded from a trusted site like Bukkit, Spigot, Modrinth, Curseforge, or Poggit. According to the Bukkit site when I tried to get the plugin approved it was "not popular enough" on Bukkit with 400 or so downloads. I would really like to use this great mod in Aternos servers, and I don't know if this is a fixable issue, but I do know that the Spigot site is two to three times as popular as the Bukkit site. If the download could be attached to the Spigot site without an external download then maybe the plugin could be added to Aternos's approved plugin list.
![Image of an error in aternos suggestion menu](https://github.com/ShaneBeee/EnchBook/assets/138999502/80febdb6-4f96-4f87-b2a5-e620f3e45180)
![Image of requirements of an aternos server](https://github.com/ShaneBeee/EnchBook/assets/138999502/cd1cc1c1-8409-4d55-86a1-b8287346c4b1)

**Comment by ShaneBeee** [comment]
Hi, 
Sorry but I will not be adding my downloads directly to SpigotMC.
My plugins lead to GitHub as many others do.

I've had talks with members from the Aternos team and they're extremely rude, condescending and stuck up. 
They're fully capable of approving plugins that are put on GitHub, but they have consciously made the decision not to.

With that said, I won't be doing anything to appease them.

**Comment by NothingWorks123** [comment]
Ok then, thanks for your help!
