### ISSUE TITLE
Update to 1.16?

### ISSUE THREAD

**Issue by Ergenta** [ShaneBeee/EnchBook#5]
Hello! I was wondering if this plugin is planning on being updated to 1.16

**Comment by ShaneBeee** [comment]
Does it not work on 1.16?
Nothing changed in the API that should affect it.

**Comment by Ergenta** [comment]
I thought maybe it wouldn't add the new enchants but it does. It seems to be working correctly if you want to add 1.16 as supported on spigot

**Comment by Ergenta** [comment]
I see there's either a vanilla cap on combining books or there's no cap at all. Would you be willing to add an extra cap of 10? Or X amount? Also a perm to allow combining books past vanilla if possible

X being a variable for unknown and not roman numerals

**Comment by Ergenta** [comment]
I also noticed an error with text formatting 
<img width="128" alt="Annotation 2020-08-20 091143" src="https://user-images.githubusercontent.com/25316276/90783092-46a6e980-e2c5-11ea-8a21-49f486d4183e.png">
<img width="59" alt="Annotation 2020-08-20 091159" src="https://user-images.githubusercontent.com/25316276/90783097-47d81680-e2c5-11ea-91ad-2530208233c8.png">
There's no way to remove the brackets in the prefix

**Comment by Ergenta** [comment]
Any thoughts?
