### ISSUE TITLE
Armor Enchant Bug

### ISSUE THREAD

**Issue by AddyPete** [ShaneBeee/EnchBook#6]
I can't seem to combine Armor with Enchants with an Overlimit enchant book.

For I Example i tried to combine, **Netherite Armor with Projectile Protection IV** plus Blast **Protection X Enchant Book** in an anvil, 
this won't work. I can see them combined in the anvil but I can't seem to drag it out.

It works with tools (enchanted tool + Overlimit enchanted book), but enchanted armors wont combine with Overlimit  enchanted book. 
Also, it works when the armor has no enchant. (Example. Non-Enchanted Armor + Protection X Book)

Video Link: https://www.youtube.com/watch?v=wOfCJAZZmRw

Thank you!

**Comment by ShaneBeee** [comment]
preliminary testing:
Ok so in my first test, you are correct, the items seem to join, but I can't remove it from the anvil.

So what I know here is, EnchBook just sets the result in the anvil, as for not being able to remove it, that has nothing to do with this plugin.

At this point I don't actually know how to fix it, I'll do some research and see what I find.

To be continued...

**Comment by ShaneBeee** [comment]
UPDATE:
I figured out the reason this is happening. When combining these 2 items, the cost is `-1`... now I just have to figure out a proper way to adjust that. I don't want to just pick a static number, I may add or something.

**Comment by AddyPete** [comment]
> UPDATE: I figured out the reason this is happening. When combining these 2 items, the cost is `-1`... now I just have to figure out a proper way to adjust that. I don't want to just pick a static number, I may add or something.

okay glad you found the bug!
