### ISSUE TITLE
Plugin allows combining items with books

### ISSUE THREAD

**Issue by the1mason** [ShaneBeee/EnchBook#7]
When safe books is `true` and safe enchants is `false` players can combine safe book with safe item. For example:  
Player combines pickaxe-with-mending and mending without bypass permissions with safebooks set to `true` and safe enchants is `false.  
Expected behavior:  
Player gets Mending I  
Actual behavior:
Player gets Mending II

I think there could be another config parameter for unsafe items-books combining or it could use existing `SafeBooks`.

**Comment by ShaneBeee** [comment]
So... stupid me... I had this all setup before, but I forgot to add the actual config option to the config.
#OOPS 
The code was all written for it, I just never actually put it in config.yml, it will be in the next update, you shall see this in your config:
```yaml
# Require permission when a player attempts to combine an item and book and the level goes higher than vanilla allows
# This can be bypassed with the permission 'enchbook.bypass.vanilla_max_level_item'
Above Vanilla Item Requires Permission: false
```

**Comment by ShaneBeee** [comment]
Fixed in https://github.com/ShaneBeee/EnchBook/releases/tag/1.4.3
