### ISSUE TITLE
Problems with anvil.

### ISSUE THREAD

**Issue by SalomonPicos** [ShaneBeee/EnchBook#8]
Hi Shane! I'm SalomonPicos by Skript, you probably remember me.

I'm having a problem with the plugin. I want to allows player to just use custom enchanted books in anvil with tools and not merging enchanted book increasing their level. 

So they cannot create unsafe enchantments (sharpness 6, protection 6 etc..) but they can use it in the anvil with tools ect.

Is there a way to do this? If i disable Safe Enchants they can merge vanilla enchanted books too and create unsafe enchanted books.

Hope there's a way to do that since this is the only plugin that use anvil with vanilla enchantments i coulded find wich is good.

**Comment by SalomonPicos** [comment]
Thank you for your help, stay safe!

**Comment by ShaneBeee** [comment]
See #7, also talked about in private
